version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-09-01 to 2021-07-01 by month" --skip-existing
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv

  generate_study_asthma:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_asthma --index-date-range "2019-09-01 to 2021-07-01 by month" --skip-existing
    outputs:
      highly_sensitive:
        cohort: output/input_asthma_*.csv
  
  generate_measures_asthma:
    run: cohortextractor:latest generate_measures --study-definition study_definition_asthma --output-dir=output
    needs: [generate_study_asthma]
    outputs:
        moderately_sensitive:
          measure_csv: output/measure_no_asthma_resolved_rate.csv
  
  test_indicator_g:
    run: python:latest python analysis/test_indicator_g.py
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        csv: output/indicator_g_matching.csv
        

  check_EGFR:
    run: python:latest python analysis/check_EGFR.py
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        plots: output/BOXPLOT_*.png
        counts: output/CROSSTAB_*.csv
        
  generate_study_population_ethnicity:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ethnicity
    outputs:
      highly_sensitive:
        cohort: output/input_ethnicity.csv
      
  join_ethnicity_region:
    run: python:latest python analysis/join_ethnicity_region.py
    needs: [generate_study_population, generate_study_population_ethnicity]
    outputs:
      highly_sensitive:
        cohort: output/input*.csv

  calculate_numerators:
    run: python:latest python analysis/calculate_numerators.py
    needs: [join_ethnicity_region]
    outputs:
      highly_sensitive:
        cohort: output/inpu*.csv

  calculate_composite_indicators:
    run: python:latest python analysis/composite_indicators.py
    needs: [calculate_numerators]
    outputs:
      moderately_sensitive:
        counts: output/*_composite_measure.csv

  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition --output-dir=output
    needs: [calculate_numerators]
    outputs:
        moderately_sensitive:
          measure_csv: output/measure_*_rate.csv
  
  generate_measures_demographics:
    run: python:latest python analysis/calculate_measures.py
    needs: [calculate_numerators]
    outputs:
      moderately_sensitive:
        counts: output/indicator_measure_*.csv
  
  generate_plots:
    run: python:latest python analysis/plot_measures.py
    needs: [generate_measures, generate_measures_demographics, calculate_composite_indicators]
    outputs:
      moderately_sensitive:
        counts: output/plot_*.jpeg

  generate_notebook:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/report.ipynb --execute --to html --template basic --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --no-input
    needs: [generate_plots]
    outputs:
      moderately_sensitive:
        notebook: output/report.html
  
  run_tests:
    run: python:latest python -m pytest --junit-xml=output/pytest.xml --verbose
    outputs:
      moderately_sensitive:
        log: output/pytest.xml

