version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-09-01 to 2021-07-01 by month" --skip-existing
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv

  generate_study_egfr:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_egfr --index-date-range "2019-09-01 to 2021-07-01 by month" --skip-existing
    outputs:
      highly_sensitive:
        cohort: output/input_egfr_*.csv
  
  test_indicator_g:
    run: python:latest python analysis/test_indicator_g.py
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        csv: output/indicator_g_matching.csv
        
  check_EGFR:
    run: python:latest python analysis/check_EGFR.py
    needs: [generate_study_egfr]
    outputs:
      moderately_sensitive:
        boxplots: output/BOXPLOT_*.png
        histograms: output/HISTOGRAM_*.png
        counts: output/CROSSTAB_*.csv

  generate_study_population_ethnicity:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ethnicity
    outputs:
      highly_sensitive:
        cohort: output/input_ethnicity.csv
      
  join_ethnicity_region:
    run: python:latest python analysis/join_ethnicity_region.py
    needs: [generate_study_population, generate_study_population_ethnicity]
    outputs:
      highly_sensitive:
        cohort: output/input*.csv

  calculate_numerators:
    run: python:latest python analysis/calculate_numerators.py
    needs: [join_ethnicity_region]
    outputs:
      highly_sensitive:
        cohort: output/inpu*.csv

  calculate_composite_indicators:
    run: python:latest python analysis/composite_indicators.py
    needs: [calculate_numerators]
    outputs:
      moderately_sensitive:
        counts: output/*_composite_measure.csv

  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition --output-dir=output
    needs: [calculate_numerators]
    outputs:
        moderately_sensitive:
          measure_csv: output/measure_*_rate.csv

  generate_study_asthma:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_asthma --index-date-range "2019-09-01 to 2021-07-01 by month" --skip-existing
    outputs:
      highly_sensitive:
        cohort: output/input_asthma_*.csv
  
  generate_measures_asthma:
    run: cohortextractor:latest generate_measures --study-definition study_definition_asthma --output-dir=output
    needs: [generate_study_asthma]
    outputs:
        moderately_sensitive:
          measure_csv: output/measure_no_asthma_resolved_rate.csv
  
  check_asthma:
    run: python:latest python analysis/check_asthma.py
    needs: [generate_measures, generate_measures_asthma]
    outputs:
      moderately_sensitive:
        csv: output/asthma_sum.csv
  
  generate_measures_demographics:
    run: python:latest python analysis/calculate_measures.py
    needs: [calculate_numerators]
    outputs:
      moderately_sensitive:
        counts: output/indicator_measure_*.csv
  
  generate_plots:
    run: python:latest python analysis/plot_measures.py
    needs: [generate_measures, generate_measures_demographics, calculate_composite_indicators]
    outputs:
      moderately_sensitive:
        counts: output/plot_*.jpeg

  indicator_saturation_a:
    run: r:latest analysis/indicator_saturation_analysis.R -I a -T date -C practice -f -v -i output -o output/indicator_saturation measure_indicator_a_rate.csv 
    needs: [generate_measures, generate_measures_demographics, calculate_composite_indicators]
    outputs:
      highly_sensitive:
        plots: output/indicator_saturation/indicator_saturation_a/figures/*.png
        rdat: output/indicator_saturation/indicator_saturation_a/*.RData
        csv: output/indicator_saturation/indicator_saturation_a/*.csv
  
  indicator_saturation_b:
    run: r:latest analysis/indicator_saturation_analysis.R -I b -T date -C practice -f -v -i output -o output/indicator_saturation measure_indicator_b_rate.csv 
    needs: [generate_measures, generate_measures_demographics, calculate_composite_indicators]
    outputs:
      highly_sensitive:
        plots: output/indicator_saturation/indicator_saturation_b/figures/*.png
        rdat: output/indicator_saturation/indicator_saturation_b/*.RData
        csv: output/indicator_saturation/indicator_saturation_b/*.csv

  indicator_saturation_c:
    run: r:latest analysis/indicator_saturation_analysis.R -I c -T date -C practice -f -v -i output -o output/indicator_saturation measure_indicator_c_rate.csv 
    needs: [generate_measures, generate_measures_demographics, calculate_composite_indicators]
    outputs:
      highly_sensitive:
        plots: output/indicator_saturation/indicator_saturation_c/figures/*.png
        rdat: output/indicator_saturation/indicator_saturation_c/*.RData
        csv: output/indicator_saturation/indicator_saturation_c/*.csv

  indicator_saturation_d:
    run: r:latest analysis/indicator_saturation_analysis.R -I d -T date -C practice -f -v -i output -o output/indicator_saturation measure_indicator_d_rate.csv 
    needs: [generate_measures, generate_measures_demographics, calculate_composite_indicators]
    outputs:
      highly_sensitive:
        plots: output/indicator_saturation/indicator_saturation_d/figures/*.png
        rdat: output/indicator_saturation/indicator_saturation_d/*.RData
        csv: output/indicator_saturation/indicator_saturation_d/*.csv

  indicator_saturation_e:
    run: r:latest analysis/indicator_saturation_analysis.R -I e -T date -C practice -f -v -i output -o output/indicator_saturation measure_indicator_e_rate.csv 
    needs: [generate_measures, generate_measures_demographics, calculate_composite_indicators]
    outputs:
      highly_sensitive:
        plots: output/indicator_saturation/indicator_saturation_e/figures/*.png
        rdat: output/indicator_saturation/indicator_saturation_e/*.RData
        csv: output/indicator_saturation/indicator_saturation_e/*.csv

  indicator_saturation_f:
    run: r:latest analysis/indicator_saturation_analysis.R -I f -T date -C practice -f -v -i output -o output/indicator_saturation measure_indicator_f_rate.csv 
    needs: [generate_measures, generate_measures_demographics, calculate_composite_indicators]
    outputs:
      highly_sensitive:
        plots: output/indicator_saturation/indicator_saturation_f/figures/*.png
        rdat: output/indicator_saturation/indicator_saturation_f/*.RData
        csv: output/indicator_saturation/indicator_saturation_f/*.csv
        
  indicator_saturation_g:
    run: r:latest analysis/indicator_saturation_analysis.R -I g -T date -C practice -f -v -i output -o output/indicator_saturation measure_indicator_g_rate.csv 
    needs: [generate_measures, generate_measures_demographics, calculate_composite_indicators]
    outputs:
      highly_sensitive:
        plots: output/indicator_saturation/indicator_saturation_g/figures/*.png
        rdat: output/indicator_saturation/indicator_saturation_g/*.RData
        csv: output/indicator_saturation/indicator_saturation_g/*.csv

  indicator_saturation_i:
    run: r:latest analysis/indicator_saturation_analysis.R -I i -T date -C practice -f -v -i output -o output/indicator_saturation measure_indicator_i_rate.csv 
    needs: [generate_measures, generate_measures_demographics, calculate_composite_indicators]
    outputs:
      highly_sensitive:
        plots: output/indicator_saturation/indicator_saturation_i/figures/*.png
        rdat: output/indicator_saturation/indicator_saturation_i/*.RData
        csv: output/indicator_saturation/indicator_saturation_i/*.csv

  indicator_saturation_k:
    run: r:latest analysis/indicator_saturation_analysis.R -I k -T date -C practice -f -v -i output -o output/indicator_saturation measure_indicator_k_rate.csv 
    needs: [generate_measures, generate_measures_demographics, calculate_composite_indicators]
    outputs:
      highly_sensitive:
        plots: output/indicator_saturation/indicator_saturation_k/figures/*.png
        rdat: output/indicator_saturation/indicator_saturation_k/*.RData
        csv: output/indicator_saturation/indicator_saturation_k/*.csv

  indicator_saturation_ac:
    run: r:latest analysis/indicator_saturation_analysis.R -I ac -T date -C practice -f -v -i output -o output/indicator_saturation measure_indicator_ac_rate.csv 
    needs: [generate_measures, generate_measures_demographics, calculate_composite_indicators]
    outputs:
      highly_sensitive:
        plots: output/indicator_saturation/indicator_saturation_ac/figures/*.png
        rdat: output/indicator_saturation/indicator_saturation_ac/*.RData
        csv: output/indicator_saturation/indicator_saturation_ac/*.csv

  indicator_saturation_me_no_fbc:
    run: r:latest analysis/indicator_saturation_analysis.R -I me_no_fbc -T date -C practice -B indicator_me_denominator -f -v -i output -o output/indicator_saturation measure_indicator_me_no_fbc_rate.csv 
    needs: [generate_measures, generate_measures_demographics, calculate_composite_indicators]
    outputs:
      highly_sensitive:
        plots: output/indicator_saturation/indicator_saturation_me_no_fbc/figures/*.png
        rdat: output/indicator_saturation/indicator_saturation_me_no_fbc/*.RData
        csv: output/indicator_saturation/indicator_saturation_me_no_fbc/*.csv
        
  indicator_saturation_me_no_lft:
    run: r:latest analysis/indicator_saturation_analysis.R -I me_no_lft -T date -C practice -B indicator_me_denominator -f -v -i output -o output/indicator_saturation measure_indicator_me_no_lft_rate.csv 
    needs: [generate_measures, generate_measures_demographics, calculate_composite_indicators]
    outputs:
      highly_sensitive:
        plots: output/indicator_saturation/indicator_saturation_me_no_lft/figures/*.png
        rdat: output/indicator_saturation/indicator_saturation_me_no_lft/*.RData
        csv: output/indicator_saturation/indicator_saturation_me_no_lft/*.csv

  indicator_saturation_li:
    run: r:latest analysis/indicator_saturation_analysis.R -I li -T date -C practice -f -v -i output -o output/indicator_saturation measure_indicator_li_rate.csv 
    needs: [generate_measures, generate_measures_demographics, calculate_composite_indicators]
    outputs:
      highly_sensitive:
        plots: output/indicator_saturation/indicator_saturation_li/figures/*.png
        rdat: output/indicator_saturation/indicator_saturation_li/*.RData
        csv: output/indicator_saturation/indicator_saturation_li/*.csv

  indicator_saturation_am:
    run: r:latest analysis/indicator_saturation_analysis.R -I am -T date -C practice -f -v -i output -o output/indicator_saturation measure_indicator_am_rate.csv 
    needs: [generate_measures, generate_measures_demographics, calculate_composite_indicators]
    outputs:
      highly_sensitive:
        plots: output/indicator_saturation/indicator_saturation_am/figures/*.png
        rdat: output/indicator_saturation/indicator_saturation_am/*.RData
        csv: output/indicator_saturation/indicator_saturation_am/*.csv

  combine_indicator_saturation_data:
    run: r:latest analysis/combine_indicator_saturation_output.R output/indicator_saturation output/indicator_saturation/combined
    needs: [indicator_saturation_a, indicator_saturation_b, indicator_saturation_c, indicator_saturation_d, indicator_saturation_e, indicator_saturation_f, indicator_saturation_g, indicator_saturation_i, indicator_saturation_k, indicator_saturation_ac, indicator_saturation_me_no_fbc, indicator_saturation_me_no_lft, indicator_saturation_li, indicator_saturation_am]
    outputs:
      highly_sensitive:
        compiled_indicator_saturation: output/indicator_saturation/combined/*
  
  # generate_notebook:
  #   run: jupyter:latest jupyter nbconvert /workspace/analysis/report.ipynb --execute --to html --template basic --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --no-input
  #   needs: [generate_plots]
  #   outputs:
  #     moderately_sensitive:
  #       notebook: output/report.html
  
  run_tests:
    run: python:latest python -m pytest --junit-xml=output/pytest.xml --verbose
    outputs:
      moderately_sensitive:
        log: output/pytest.xml

