version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-01-01 to 2020-01-01 by month"
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv
  
  calculate_numerators:
    run: python:latest analysis/calculate_numerators.py
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        cohort: output/input*.csv

  calculate_composite_indicators:
    run: python:latest analysis/composite_indicators.py
    needs: [calculate_numerators]
    outputs:
      highly_sensitive:
        cohort: output/inpu*.csv


  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition --output-dir=output
    needs: [calculate_composite_indicators]
    outputs:
        moderately_sensitive:
          measure_csv: output/measure_*_rate.csv

