version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-01-01 to 2020-01-01 by month"
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv

  check_EGFR:
    run: python:latest analysis/check_EGFR.py
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        plots: output/BOXPLOT_*.png
        counts: output/CROSSTAB_*.csv
        
  generate_study_population_ethnicity:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ethnicity
    outputs:
      highly_sensitive:
        cohort: output/input_ethnicity.csv
      
  join_ethnicity_region:
    run: python:latest python analysis/join_ethnicity_region.py
    needs: [generate_study_population, generate_study_population_ethnicity]
    outputs:
      highly_sensitive:
        cohort: output/input*.csv

  calculate_numerators:
    run: python:latest analysis/calculate_numerators.py
    needs: [join_ethnicity_region]
    outputs:
      highly_sensitive:
        cohort: output/inpu*.csv

  calculate_composite_indicators:
    run: python:latest analysis/composite_indicators.py
    needs: [calculate_numerators]
    outputs:
      moderately_sensitive:
        counts: output/*_composite_measure.csv

  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition --output-dir=output
    needs: [calculate_numerators]
    outputs:
        moderately_sensitive:
          measure_csv: output/measure_*_rate.csv
  
  generate_measures_demographics:
    run: python:latest analysis/calculate_measures.py
    needs: [calculate_numerators]
    outputs:
      moderately_sensitive:
        counts: output/indicator_measure_*.csv
  
  generate_plots:
    run: python:latest analysis/plot_measures.py
    needs: [generate_measures, generate_measures_demographics]
    outputs:
      moderately_sensitive:
        counts: output/plot_*.jpeg
